#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;



$root = ($polecenie);


$polecenie = (uruchom | włącz){start}  $co | (zamknij | wyłącz){stop} $co | (wycisz | cisza | włącz dźwięk){wycisz} |

(wstrzymaj | zatrzymaj){stop} | (podgłośnij o){podgłośnij} $o_ile | (ścisz o){ścisz} $o_ile | zaznacz wszystko{ctrl+a} |

zresetuj  (głośność | dźwięk) {volume_reset } | (w górę | wyżej){page_up} | (w dół | niżej){page_down} |

cofnij {back} | (zapisz | zachowaj) {save} | (wydrukuj | do drukarki){print};

$co = edytor tekstu {text} | odtwarzacz muzyki{music} | (wiersz poleceń | terminal | konsole){terminal} | przeglądarkę{web} | przeglądarkę plików{files}  $gdzie | effekty{efx} ;

$gdzie = (domowy | katalog domowy | mój folder){home};

$o_ile = jeden{1} | dwa{2} | trzy{3} | cztery{4} | pięć {5};