#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;



$root = $polecenie <1-10>;


$polecenie = uruchom | podgłośnij | ścisz | wstrzymaj | wyłącz | komputer | zablokuj | jeden | wycisz | blank;
